spring.datasource.url=jdbc:postgresql://hyper-markhor-11748.jxf.gcp-europe-west1.cockroachlabs.cloud:26257/defaultdb?sslmode=require
spring.datasource.username=tim
spring.datasource.password=0nnc7yxyn57SlLJAo2FGzg

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Prepre?i avtomatsko spreminjanje baze
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
